const Map<String, String> English = {
  // App Name
  'appName': 'XPRESSFLY',
  'welcomeTo': 'Welcome to\nXPRESSFLY',

  // Authentication
  'number': 'Number',
  'enterYourNumber': 'Enter your number',
  'pleaseEnterPhoneNumber': 'Please enter your phone number',
  'phoneNumberMustBe10Digits': 'Phone number must be 10 digits',
  'getOtp': 'GET OTP',
  'verifyYourNumberWithOtp': 'Verify your\nNumber with OTP',
  'enterOtp': 'Enter OTP',
  'pleaseEnterOtp': 'Please enter OTP',
  'pleaseEnterValidOtp': 'Please enter valid OTP',
  'confirm': 'CONFIRM',
  'didntReceiveOtp': "Didn't receive OTP? ",
  'resend': 'Resend',
  'termsConditions': 'Terms & Conditions',
  'letsGetStarted': "Let's get started",
  'login': 'LOGIN',
  'signUp': 'SIGN UP',

  // Join As Screen
  'joinAs': 'Join As',
  'selectYourTypeOfAccount': 'Select your type of account',
  'asDriver': 'As Driver',
  'asDriverDescription':
      'A reliable driver for timely\nand efficient parcel deliveries',
  'asCustomer': 'As Customer',
  'asCustomerDescription':
      'A customer who can book\na vehicle and send parcels',

  // Home Screen
  'hello': 'Hello',
  'verificationRequired': 'Verification Required',
  'verifyAccountWithAadhar': 'Verify Your Account With Your Aadhar Card',
  'verifyAccountWithDetails': 'Verify Your Account With Your Details',
  'safeDelivery': 'Safe Delivery',
  'fastDelivery': 'Fast Delivery',
  'selectVehicle': 'Select Vehicle',
  'bookAOrder': 'Book a Order',

  // Driver Home Screen
  'todayEarning': 'Today Earning',
  'totalTrips': 'Total Trips',
  'totalDistance': 'Total Distance',
  'vehicleList': 'Vehicle List',
  'addVehicle': 'Add Vehicle',
  'searchVehicle': 'Search Vehicle',
  'noVehiclesFound': 'No vehicles found',
  'addYourFirstVehicle': 'Add your first vehicle to get started',
  'unknownVehicle': 'Unknown Vehicle',
  'noNumber': 'No Number',
  'address': 'address',
  'driver': 'Driver',

  // Book Order
  'back': 'Back',
  'next': 'Next',
  'submit': 'Submit',
  'slideToConfirm': 'Slide to Confirm',
  'orderCreatedSuccessfully': 'Order Created Successfully with ID:',

  // Drawer
  'home': 'Home',
  'orderRequest': 'Order Request',
  'orderHistory': 'Order History',
  'profile': 'Profile',
  'language': 'Language',
  'termsCondition': 'Terms & Condition',
  'privacyPolicy': 'Privacy Policy',
  'helpSupport': 'Help & Support',
  'logout': 'Logout',
  'logoutConfirmation': 'Are you sure you want to logout?',
  'cancel': 'Cancel',

  // Form Fields
  'enterPickupLocation': 'Enter Pickup Location with Pin-code',
  'enterDropLocation': 'Enter Drop Location with Pin-code',
  'enterYourName': 'Enter your name',
  'exampleName': 'ex. Rohit Shah',
  'examplePhone': 'ex. 98765 43210',
  'exampleOtherName': 'ex. Mohit Shah',
  'exampleItemDescription': 'ex. 15-20 kg Simple table',
  'selectDate': 'Select date',
  'fromTime': 'From time (09:00)',
  'toTime': 'To time (02:00 PM)',
  'titleOfItem': 'Title of the item',
  'userEmailExample': 'user@example.com',
  'enterYourCity': 'Enter your city',
  'addressExample': '90, Houses, Surat, Gujarat - 395010',
  'enterAccountHolderName': 'Enter account holder name',

  // Verification & Upload
  'uploadFront': 'Upload front',
  'uploadBack': 'Upload back',
  'frontImage': 'Front Image',
  'backImage': 'Back Image',
  'saveDetails': 'Save Details',

  // Profile
  'editProfile': 'Edit Profile',

  // General
  'ok': 'OK',

  // English
  'selectLanguage': 'Select Language',
  'selectYourLanguage': 'Select Your Language',

  'yourDetails': 'Your Details',
  'yourName': 'Your name',
  'yourEmail': 'Your Email',
  'yourCity': 'Your city',
  'yourPincode': 'Your pincode',
  'pleaseEnterYourName': 'Please enter your name',
  'pleaseEnterYourEmail': 'Please enter your email',
  'pleaseEnterYourCity': 'Please enter your city',
  'pleaseEnterValidPincode': 'Please enter valid pincode',
  'phoneNumber': 'Phone Number',
  'email': 'Email',
  'pincode': 'Pincode',
  'city': 'City',
  'gallery': 'Gallery',
  'camera': 'Camera',
  'tapToUpload': 'Tap to upload',
  'orderDetails': 'Order Details',
  'receiverNameMobile': 'Receiver Name & Mobile no.',
  'senderNameMobile': 'Sender Name & Mobile no.',
  'pleaseEnterReceiverName': 'Please enter receiver name',
  'pleaseEnterReceiverMobile': 'Please enter receiver mobile no.',
  'approxWeight': 'Approx Weight of Your Items',
  'pleaseEnterOrderWeight': 'Please enter order weight',
  'pleaseEnterPickupLocation': 'Please enter pickup location',
  'pleaseEnterDropLocation': 'Please enter drop location',
  'zipCodeMustBe6To9Characters': 'ZIP code must be 6 to 9 characters',
  'whatWouldYouLikeToSend': 'What would you like to send?',
  'pleaseEnterOrderTitle': 'Please enter order title',
  'selectOrUploadImage': 'Select or upload image',
  'dontForgetToPack': 'Don\'t forget to pack your items before shipping',
  'selectImage': 'Select Image',
  'choosePickupDateTime': 'Choose the pickup date & time',
  'pleaseSelectPickupDate': 'Please select pickup date',
  'time': 'Time',
  'pleaseEnterFromTime': 'Please enter from time',
  'pleaseEnterToTime': 'Please enter to time',
  'selectPaymentType': 'Select Payment Type',
  'payWithUpi': 'Pay With UPI',
  'fastSecurePayment': 'Fast & secure payment\nwith no extra charges.',
  'error': 'Error',
  'success': 'Success',
  'save': 'Save',
  'dontForgetToPackYourItemsBeforeShipping':
      "Don't forget to pack your items before shipping",
  'pleaseEnterMobileNumber': 'Please enter mobile number',
  'mobileNumberMustBe10Digits': 'Mobile number must be 10 digits',
  'pleaseEnterEmail': 'Please enter email',
  'pleaseEnterPincode': 'Please enter pincode',
  'pincodeMustBe6Digits': 'Pincode must be 6 digits',
  'pleaseEnterCity': 'Please enter city',
  'pleaseEnterAddress': 'Please enter address',
  'accountHolderName': 'Account Holder Name',
  'pleaseEnterAccountHolderName': 'Please enter account holder name',
  'pleaseEnterAccountNumber': 'Please enter account number',
  'accountNumber': 'Account Number',
  'ifscCode': 'IFSC Code',
  'pleaseEnterIfscCode': 'Please enter IFSC Code',
  'ifscCodeMustBe11Characters': 'IFSC Code must be 11 characters',
  'bankDetails': 'Bank Details',
  'bankAccountNumber': 'Bank Account Number',
  'bankAccountName': 'Bank Account Name',
  'bankIfsc': 'Bank IFSC',
  'pleaseEnterBankAccountNumber': 'Please enter bank account number',
  'pleaseEnterBankAccountName': 'Please enter bank account name',
  'pleaseEnterBankIfsc': 'Please enter bank IFSC',
  'yourBankDetails': 'Your Bank Details',
  'yourVehicleType': 'Your Vehicle Type',
  'areYouSure': 'Are you sure?',
  'doYouWantToDeleteThisVehicle':
      'Do you want to delete this vehicle?\nThis action cannot be undone.',
  'sure': 'Sure',
  'successfullyDeleted': 'Successfully Deleted',
  'fastReliableDeliveredYourWay': 'Fast, Reliable,\nDelivered Your Way',
  'trackScheduleAndDeliverWithEase':
      'Track, schedule, and deliver with ease.\nYour delivery, your control.',
  'verification': 'Verification',
  'uploadYourAadhaarImages': 'Upload your Aadhaar images',
  'uploadYourLicenceImages': 'Upload your Licence images',
  'upload': 'Upload',
  'alert': 'Alert',
  'pleaseUploadAadhaarFrontImage': 'Please upload Aadhaar front image',
  'pleaseUploadAadhaarBackImage': 'Please upload Aadhaar back image',
  'pleaseUploadLicenseFrontImage': 'Please upload License front image',
  'pleaseUploadLicenseBackImage': 'Please upload License back image',

  // Add these to the English map
  'trackOrder': 'Track Order',
  'yourOrder': 'Your Order',
  'estimatedDeliveryTime': 'Estimated delivery time',
  'requestConfirmation': 'Request Confirmation',
  'weWillPickupYourItemSoon': 'We will pickup your item soon',
  'inTransit': 'In Transit',
  'yourItemWasPickedUp': 'Your item was picked up',
  'outForDelivery': 'Out for Delivery',
  'yourParcelIsOnTheWay': 'Your parcel is on the way',
  'delivered': 'Delivered',
  'parcelDeliveredSuccessfully': 'Parcel delivered successfully',
  'orderNotConfirmed': 'Order Not Confirmed',
  'noDriverAcceptedYourRequest': 'No driver accepted your request.',
  'tryAgain': 'Try Again',
  'backToHome': 'Back to Home',
  'orderSuccessful': 'Order Successful!',
  'yourOrderHasBeenPlacedAndProcessingHasStarted':
      'Your order has been placed and processing\nhas started',
  'close': 'Close',
  'trackYourOrder': 'Track your order',
  'selectDeliveryArea': 'Select Delivery Area',
  'sameCity': 'Same City',
  'otherCity': 'Other City',
  'almostThere': 'Almost there',
  'lookingForNearbyDrivers': 'Looking for nearby drivers...',
  'youllBeRedirectedOnceYourRequestIsAccepted':
      'You\'ll be redirected once your request is accepted.',
  'fullName': 'Full Name',
  'vehicleModel': 'Vehicle Model',
  'vehicleNumber': 'Vehicle Number',
  'vehicleType': 'Vehicle Type',
  'whereYouCanDeliver': 'Where You Can Deliver',
  'uploadYourRcBookImages': 'Upload your RC book images',
  'uploadAadharFrontBack': 'Upload Aadhar Front & Back',
  'uploadRcBookFrontBack': 'Upload RC Book Front & Back',
  'pleaseEnterFullName': 'Please enter full name',
  'pleaseEnterVehicleModel': 'Please enter vehicle model',
  'pleaseEnterVehicleNumber': 'Please enter vehicle number',
  'pleaseSelectVehicleType': 'Please select vehicle type',
  'pleaseEnterDeliveryPincodes': 'Please enter delivery pincodes',
  'allPincodesMustBe6Digits': 'All pincodes must be 6 digits',
  'vehicleDetails': 'Vehicle Details',
  'editDetails': 'Edit Details',
  'activeOrders': 'Active Orders',
  'pastOrders': 'Past Orders',
  'noActiveOrders': 'No active orders',
  'noPastOrders': 'No past orders',
  'pickupPoint': 'Pickup Point',
  'destination': 'Destination',
  'payment': 'Payment',
  'distance': 'Distance',
  'today': 'Today',
  'deliveryDetails': 'DELIVERY DETAILS',
  'pickPoint': 'Pick\nPoint',
  'dropPoint': 'Drop\nPoint',
  'reject': 'Reject',
  'oops': 'Oops!',
  'noMoreOrderRightNow': 'No more order right now',
  'swipeToAccept': 'Swipe to Accept',
  'accepted': 'Accepted',
  'yourProfile': 'Your Profile',
  'pinCode': 'Pin code',
  'serviceablePinCodesAsSelectedByDriver':
      'Serviceable pin codes as selected by the driver',
  'delete': 'Delete',
  'edit': 'Edit',
  'pleaseUploadRCBookFrontImage': "Please upload RC book front image",
  'pleaseUploadRCBookBackImage': "Please upload RC book back image",
  'Retry': 'Retry',
  'noOrdersFound': 'No orders found',
};
