const Map<String, String> Hindi = {
  // App Name
  'appName': 'एक्सप्रेसफ्लाई',
  'welcomeTo': 'स्वागत है\nएक्सप्रेसफ्लाई में',

  // Authentication
  'number': 'नंबर',
  'enterYourNumber': 'अपना नंबर दर्ज करें',
  'pleaseEnterPhoneNumber': 'कृपया अपना फोन नंबर दर्ज करें',
  'phoneNumberMustBe10Digits': 'फोन नंबर 10 अंकों का होना चाहिए',
  'getOtp': 'OTP प्राप्त करें',
  'verifyYourNumberWithOtp': 'OTP के साथ अपना\nनंबर सत्यापित करें',
  'enterOtp': 'OTP दर्ज करें',
  'pleaseEnterOtp': 'कृपया OTP दर्ज करें',
  'pleaseEnterValidOtp': 'कृपया वैध OTP दर्ज करें',
  'confirm': 'पुष्टि करें',
  'didntReceiveOtp': 'OTP प्राप्त नहीं हुआ? ',
  'resend': 'पुनः भेजें',
  'termsConditions': 'नियम और शर्तें',
  'letsGetStarted': 'चलिए शुरू करते हैं',
  'login': 'लॉगिन',
  'signUp': 'साइन अप',

  // Join As Screen
  'joinAs': 'के रूप में शामिल हों',
  'selectYourTypeOfAccount': 'अपने खाते का प्रकार चुनें',
  'asDriver': 'ड्राइवर के रूप में',
  'asDriverDescription':
      'समय पर और कुशल\nपार्सल डिलीवरी के लिए एक विश्वसनीय ड्राइवर',
  'asCustomer': 'ग्राहक के रूप में',
  'asCustomerDescription':
      'एक ग्राहक जो वाहन बुक कर सकता है\nऔर पार्सल भेज सकता है',

  // Home Screen
  'hello': 'नमस्ते',
  'verificationRequired': 'सत्यापन आवश्यक',
  'verifyAccountWithAadhar':
      'अपने आधार कार्ड के साथ अपने खाते को सत्यापित करें',
  'verifyAccountWithDetails': 'अपने विवरण के साथ अपने खाते को सत्यापित करें',
  'safeDelivery': 'सुरक्षित डिलीवरी',
  'fastDelivery': 'तेज़ डिलीवरी',
  'selectVehicle': 'वाहन चुनें',
  'bookAOrder': 'आर्डर बुक करें',

  // Driver Home Screen
  'todayEarning': 'आज की कमाई',
  'totalTrips': 'कुल यात्राएं',
  'totalDistance': 'कुल दूरी',
  'vehicleList': 'वाहन सूची',
  'addVehicle': 'वाहन जोड़ें',
  'searchVehicle': 'वाहन खोजें',
  'noVehiclesFound': 'कोई वाहन नहीं मिला',
  'addYourFirstVehicle': 'शुरुआत करने के लिए अपना पहला वाहन जोड़ें',
  'unknownVehicle': 'अज्ञात वाहन',
  'noNumber': 'नंबर नहीं',
  'address': 'पता',
  'driver': 'ड्राइवर',

  // Book Order
  'back': 'वापस',
  'next': 'आगे',
  'submit': 'जमा करें',
  'slideToConfirm': 'पुष्टि करने के लिए स्लाइड करें',
  'orderCreatedSuccessfully': 'आर्डर सफलतापूर्वक बनाया गया ID के साथ:',

  // Drawer
  'home': 'होम',
  'orderRequest': 'आर्डर अनुरोध',
  'orderHistory': 'आर्डर इतिहास',
  'profile': 'प्रोफ़ाइल',
  'language': 'भाषा',
  'termsCondition': 'नियम और शर्तें',
  'privacyPolicy': 'गोपनीयता नीति',
  'helpSupport': 'सहायता और समर्थन',
  'logout': 'लॉग आउट',
  'logoutConfirmation': 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
  'cancel': 'रद्द करें',

  // Form Fields
  'enterPickupLocation': 'पिकअप स्थान पिन-कोड के साथ दर्ज करें',
  'enterDropLocation': 'ड्रॉप स्थान पिन-कोड के साथ दर्ज करें',
  'enterYourName': 'अपना नाम दर्ज करें',
  'exampleName': 'जैसे. रोहित शाह',
  'examplePhone': 'जैसे. 98765 43210',
  'exampleOtherName': 'जैसे. मोहित शाह',
  'exampleItemDescription': 'जैसे. 15-20 किग्रा साधारण मेज',
  'selectDate': 'दिनांक चुनें',
  'fromTime': 'समय से (09:00)',
  'toTime': 'समय तक (02:00 PM)',
  'titleOfItem': 'वस्तु का शीर्षक',
  'userEmailExample': 'user@example.com',
  'enterYourCity': 'अपना शहर दर्ज करें',
  'addressExample': '90, घर, सूरत, गुजरात - 395010',
  'enterAccountHolderName': 'खाताधारक का नाम दर्ज करें',

  // Verification & Upload
  'uploadFront': 'सामने अपलोड करें',
  'uploadBack': 'पीछे अपलोड करें',
  'frontImage': 'सामने की छवि',
  'backImage': 'पीछे की छवि',
  'saveDetails': 'विवरण सहेजें',

  // Profile
  'editProfile': 'प्रोफ़ाइल संपादित करें',

  // General
  'ok': 'ठीक है',

  // Hindi
  'selectLanguage': 'भाषा चुनें',
  'selectYourLanguage': 'अपनी भाषा चुनें',

  'yourDetails': 'आपका विवरण',
  'yourName': 'आपका नाम',
  'yourEmail': 'आपका ईमेल',
  'yourCity': 'आपका शहर',
  'yourPincode': 'आपका पिनकोड',
  'pleaseEnterYourName': 'कृपया अपना नाम दर्ज करें',
  'pleaseEnterYourEmail': 'कृपया अपना ईमेल दर्ज करें',
  'pleaseEnterYourCity': 'कृपया अपना शहर दर्ज करें',
  'pleaseEnterValidPincode': 'कृपया वैध पिनकोड दर्ज करें',
  'phoneNumber': 'फोन नंबर',
  'email': 'ईमेल',
  'pincode': 'पिनकोड',
  'city': 'शहर',
  'gallery': 'गैलरी',
  'camera': 'कैमरा',
  'tapToUpload': 'अपलोड करने के लिए टैप करें',
  'orderDetails': 'आर्डर विवरण',
  'receiverNameMobile': 'प्राप्तकर्ता नाम और मोबाइल नंबर',
  'senderNameMobile': 'भेजने वाला नाम और मोबाइल नंबर',
  'pleaseEnterReceiverName': 'कृपया प्राप्तकर्ता का नाम दर्ज करें',
  'pleaseEnterReceiverMobile': 'कृपया प्राप्तकर्ता का मोबाइल नंबर दर्ज करें',
  'approxWeight': 'आपके आइटम का अनुमानित वजन',
  'pleaseEnterOrderWeight': 'कृपया आर्डर का वजन दर्ज करें',
  'pleaseEnterPickupLocation': 'कृपया पिकअप स्थान दर्ज करें',
  'pleaseEnterDropLocation': 'कृपया ड्रॉप स्थान दर्ज करें',
  'zipCodeMustBe6To9Characters': 'ZIP कोड 6 से 9 अक्षरों का होना चाहिए',
  'whatWouldYouLikeToSend': 'आप क्या भेजना चाहेंगे?',
  'pleaseEnterOrderTitle': 'कृपया आर्डर शीर्षक दर्ज करें',
  'selectOrUploadImage': 'छवि चुनें या अपलोड करें',
  'dontForgetToPack': 'शिपिंग से पहले अपने आइटम पैक करना न भूलें',
  'selectImage': 'छवि चुनें',
  'choosePickupDateTime': 'पिकअप दिनांक और समय चुनें',
  'pleaseSelectPickupDate': 'कृपया पिकअप दिनांक चुनें',
  'time': 'समय',
  'pleaseEnterFromTime': 'कृपया समय से दर्ज करें',
  'pleaseEnterToTime': 'कृपया समय तक दर्ज करें',
  'selectPaymentType': 'भुगतान प्रकार चुनें',
  'payWithUpi': 'UPI के साथ भुगतान करें',
  'fastSecurePayment': 'तेज़ और सुरक्षित भुगतान\nबिना अतिरिक्त शुल्क के।',
  'error': 'त्रुटि',
  'success': 'सफलता',
  'save': 'सहेजें',
  'dontForgetToPackYourItemsBeforeShipping':
      "शिपिंग से पहले अपने आइटम पैक करना न भूलें",
  'pleaseEnterMobileNumber': 'कृपया मोबाइल नंबर दर्ज करें',
  'mobileNumberMustBe10Digits': 'मोबाइल नंबर 10 अंकों का होना चाहिए',
  'pleaseEnterEmail': 'कृपया ईमेल दर्ज करें',
  'pleaseEnterPincode': 'कृपया पिनकोड दर्ज करें',
  'pleaseEnterCity': 'कृपया शहर दर्ज करें',
  'pleaseEnterAddress': 'कृपया पता दर्ज करें',
  'pleaseEnterAccountHolderName': 'कृपया खाताधारक का नाम दर्ज करें',
  'pleaseEnterAccountNumber': 'कृपया बैंक खाता संख्या दर्ज करें',
  'pincodeMustBe6Digits': 'पिनकोड 6 अंकों का होना चाहिए',
  'accountHolderName': 'खाताधारक का नाम',
  'accountNumber': 'बैंक खाता संख्या',
  'ifscCode': 'IFSC कोड',
  'pleaseEnterIfscCode': 'कृपया IFSC कोड दर्ज करें',
  'ifscCodeMustBe11Characters': 'IFSC कोड 11 अक्षरों का होना चाहिए',
  'pleaseEnterBankAccountNumber': 'कृपया बैंक खाता संख्या दर्ज करें',
  'pleaseEnterBankAccountName': 'कृपया बैंक खाता नाम दर्ज करें',
  'pleaseEnterBankIfsc': 'कृपया बैंक IFSC दर्ज करें',
  'bankDetails': 'आपका बैंक विवरण',
  'bankAccountNumber': 'बैंक खाता संख्या',
  'bankAccountName': 'बैंक खाता नाम',
  'yourBankDetails': 'आपका बैंक विवरण',
  'yourVehicleType': 'आपका वाहन प्रकार',
  'areYouSure': 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
  'doYouWantToDeleteThisVehicle':
      'क्या आप वाकई इस वाहन को हटाना चाहते हैं?\nयह क्रिया पुनरावर्ती नहीं की जा सकती है।',
  'sure': 'वाकई',
  'successfullyDeleted': 'सफलतापूर्वक हटाया गया',
  'fastReliableDeliveredYourWay':
      'तेज़, विश्वसनीय,\nआपके द्वारा डिलीवर किया गया',
  'trackScheduleAndDeliverWithEase':
      'ट्रैक, अनुस्थापित, और सुविधाजनक रूप से डिलीवर करें।\nआपकी डिलीवरी, आपका नियंत्रण।',
  'verification': 'सत्यापन',
  'uploadYourAadhaarImages': 'आपका आधार कार्ड छवियां अपलोड करें',
  'uploadYourLicenceImages': 'आपका लाइसेंस छवियां अपलोड करें',
  'upload': 'अपलोड करें',
  'alert': 'चेतावनी',
  'pleaseUploadAadhaarFrontImage':
      'कृपया आधार कार्ड का सामने वाला चित्र अपलोड करें',
  'pleaseUploadAadhaarBackImage':
      'कृपया आधार कार्ड का पीछे वाला चित्र अपलोड करें',
  'pleaseUploadLicenseFrontImage':
      'कृपया लाइसेंस का सामने वाला चित्र अपलोड करें',
  'pleaseUploadLicenseBackImage': 'कृपया लाइसेंस का पीछे वाला चित्र अपलोड करें',

  // Add these to the Hindi map
  'trackOrder': 'ऑर्डर ट्रैक करें',
  'yourOrder': 'आपका ऑर्डर',
  'estimatedDeliveryTime': 'अनुमानित डिलीवरी समय',
  'requestConfirmation': 'अनुरोध पुष्टि',
  'weWillPickupYourItemSoon': 'हम जल्द ही आपका सामान उठाएंगे',
  'inTransit': 'ट्रांजिट में',
  'yourItemWasPickedUp': 'आपका सामान उठा लिया गया',
  'outForDelivery': 'डिलीवरी के लिए बाहर',
  'yourParcelIsOnTheWay': 'आपका पार्सल रास्ते में है',
  'delivered': 'डिलीवर किया गया',
  'parcelDeliveredSuccessfully': 'पार्सल सफलतापूर्वक डिलीवर किया गया',
  'orderNotConfirmed': 'ऑर्डर पुष्टि नहीं हुई',
  'noDriverAcceptedYourRequest':
      'किसी भी ड्राइवर ने आपके अनुरोध को स्वीकार नहीं किया।',
  'tryAgain': 'पुनः प्रयास करें',
  'backToHome': 'होम पर वापस जाएं',
  'orderSuccessful': 'ऑर्डर सफल!',
  'yourOrderHasBeenPlacedAndProcessingHasStarted':
      'आपका ऑर्डर रखा गया है और प्रसंस्करण\nशुरू हो गया है',
  'close': 'बंद करें',
  'trackYourOrder': 'अपना ऑर्डर ट्रैक करें',
  'selectDeliveryArea': 'डिलीवरी क्षेत्र चुनें',
  'sameCity': 'समान शहर',
  'otherCity': 'अन्य शहर',
  'almostThere': 'लगभग वहाँ',
  'lookingForNearbyDrivers': 'निकटवर्ती ड्राइवरों की तलाश कर रहे हैं...',
  'youllBeRedirectedOnceYourRequestIsAccepted':
      'एक बार आपका अनुरोध स्वीकार हो जाने के बाद आपको पुनर्निर्देशित किया जाएगा।',
  'fullName': 'पूरा नाम',
  'vehicleModel': 'वाहन मॉडल',
  'vehicleNumber': 'वाहन नंबर',
  'vehicleType': 'वाहन प्रकार',
  'whereYouCanDeliver': 'जहां आप डिलीवर कर सकते हैं',
  'uploadYourRcBookImages': 'अपनी RC बुक छवियां अपलोड करें',
  'uploadAadharFrontBack': 'आधार सामने और पीछे अपलोड करें',
  'uploadRcBookFrontBack': 'RC बुक सामने और पीछे अपलोड करें',
  'pleaseEnterFullName': 'कृपया पूरा नाम दर्ज करें',
  'pleaseEnterVehicleModel': 'कृपया वाहन मॉडल दर्ज करें',
  'pleaseEnterVehicleNumber': 'कृपया वाहन नंबर दर्ज करें',
  'pleaseSelectVehicleType': 'कृपया वाहन प्रकार चुनें',
  'pleaseEnterDeliveryPincodes': 'कृपया डिलीवरी पिनकोड दर्ज करें',
  'allPincodesMustBe6Digits': 'सभी पिनकोड 6 अंकों के होने चाहिए',
  'vehicleDetails': 'वाहन विवरण',
  'editDetails': 'विवरण संपादित करें',
  'activeOrders': 'सक्रिय ऑर्डर',
  'pastOrders': 'पिछले ऑर्डर',
  'noActiveOrders': 'कोई सक्रिय ऑर्डर नहीं',
  'noPastOrders': 'कोई पिछला ऑर्डर नहीं',
  'pickupPoint': 'पिकअप बिंदु',
  'destination': 'गंतव्य',
  'payment': 'भुगतान',
  'distance': 'दूरी',
  'today': 'आज',
  'deliveryDetails': 'डिलीवरी विवरण',
  'pickPoint': 'पिक\nबिंदु',
  'dropPoint': 'ड्रॉप\nबिंदु',
  'reject': 'अस्वीकार करें',
  'oops': 'ओह!',
  'noMoreOrderRightNow': 'अभी और कोई ऑर्डर नहीं',
  'swipeToAccept': 'स्वीकार करने के लिए स्वाइप करें',
  'accepted': 'स्वीकार किया गया',
  'yourProfile': 'आपकी प्रोफ़ाइल',
  'pinCode': 'पिन कोड',
  'serviceablePinCodesAsSelectedByDriver':
      'ड्राइवर द्वारा चयनित सेवा योग्य पिन कोड',
  'delete': 'हटाएं',
  'edit': 'संपादित करें',
  'pleaseUploadRCBookFrontImage': "कृपया RC बुक सामने की छवि अपलोड करें",
  'pleaseUploadRCBookBackImage': "कृपया RC बुक पीछे की छवि अपलोड करें",
  'Retry': 'पुनः प्रयास करें',
  'noOrdersFound': 'कोई ऑर्डर नहीं मिला',
  'pleaseEnterSubject': 'कृपया विषय दर्ज करें',
  'pleaseEnterYourMessage': 'कृपया अपना संदेश दर्ज करें',
  'subject': 'विषय',
  'message': 'संदेश',
  'enterSubject': 'विषय दर्ज करें',
  'enterYourMessageHere': 'अपना संदेश यहाँ दर्ज करें',
};
